const users = [
  {
    id: 1,
    email: 'odejobiolushola@gmail.com',
    password: '$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy',
    firstname: 'Odejobi',
    lastname: 'Olushola',
    phone_no: '08022440810',
    state: 'Lagos',
    city: 'Ikeja',
    occupation: 'front-end engineer',
    gender: 'Male',
    address: '257 epic tower',
    type: 'client',
    isAdmin: false,
    joined: new Date(),
  },
  {
    id: 2,
    email: 'odejobiolushola@yahoo.com',
    password: '$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy',
    firstname: 'Akinloye',
    lastname: 'Bolarinwa',
    phone_no: '08073659615',
    state: 'Oyo',
    city: 'Ogbomosho',
    occupation: 'Engineer',
    gender: 'Female',
    address: 'Bishop Smith. Admiralty Drive',
    type: 'client',
    isAdmin: false,
    joined: new Date(),
  },
  {
    id: 3,
    email: 'oyebola12@gmail.com',
    password: '$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy',
    firstname: 'Oyebola',
    lastname: 'Popoola',
    phone_no: '08022663344',
    state: 'Kwara',
    city: 'Ilorin',
    occupation: 'Baltimore',
    gender: 'Gohan',
    address: 'Shipewa county',
    type: 'staff',
    isAdmin: true,
    joined: new Date(),
  },
  {
    id: 4,
    email: 'ajax_02@gmail.com',
    password: '$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy',
    firstname: 'Adedeji',
    lastname: 'Ajani',
    phone_no: '08022663344',
    state: 'Osun',
    city: 'Ilesha',
    occupation: 'Accountant',
    gender: 'Male',
    address: 'Shipewa county',
    type: 'staff',
    isAdmin: false,
    joined: new Date(),
  },
  {
    id: 5,
    email: 'odejobiolushola@hotmail.com',
    password: '$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy',
    firstname: '',
    lastname: '',
    phone_no: '',
    state: '',
    city: '',
    occupation: '',
    gender: '',
    address: '',
    type: '',
    isAdmin: false,
    joined: new Date(),
  },
];

export default users;
