const users = [
  {
    id: 1,
    email: 'odejobiolushola@gmail.com',
    password: 'likemike009',
    firstname: 'Odejobi',
    lastname: 'Olushola',
    phone_no: '08022440810',
    state: 'Lagos',
    city: 'Ikeja',
    occupation: 'front-end engineer',
    gender: 'Male',
    address: '257 epic tower',
    dob: '10/11/2000',
    type: 'client',
    isAdmin: false,
    joined: new Date(),
  },
  {
    id: 2,
    email: 'odejobiolushola@yahoo.com',
    password: 'likemike009__',
    firstname: 'Akinloye',
    lastname: 'Bolarinwa',
    phone_no: '08073659615',
    state: 'Oyo',
    city: 'Ogbomosho',
    occupation: 'Engineer',
    gender: 'Female',
    address: 'Bishop Smith. Admiralty Drive',
    dob: '10/11/2000',
    type: 'client',
    isAdmin: false,
    joined: new Date(),
  },
  {
    id: 3,
    email: 'oyebola12@gmail.com',
    password: 'comedian12',
    firstname: 'Oyebola',
    lastname: 'Popoola',
    phone_no: '08022663344',
    state: 'Kwara',
    city: 'Ilorin',
    occupation: 'Baltimore',
    gender: 'Gohan',
    address: 'Shipewa county',
    dob: '10/11/2000',
    type: 'staff',
    isAdmin: true,
    joined: new Date(),
  },
];

export default users;
