const users = [
  {
    email: '\'olatunjidebby@gmail.com\'',
    password: '\'$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy\'',
    first_name: '\'Olatunji\'',
    last_name: '\'Deborah\'',
    user_type: '\'client\'',
    is_admin: '\'false\'',
    phone_no: '\'08022440810\'',
    state: '\'Lagos\'',
    city: '\'Ikeja\'',
    occupation: '\'front-end engineer\'',
    gender: '\'Female\'',
    address: '\'257 epic tower\'',
  },
  {
    email: '\'dj_ajax02@gmail.com\'',
    password: '\'$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy\'',
    first_name: '\'Ajani\'',
    last_name: '\'Adedeji\'',
    user_type: '\'client\'',
    is_admin: '\'false\'',
    phone_no: '\'08073659615\'',
    state: '\'Osun\'',
    city: '\'Iwo\'',
    occupation: '\'Accountant\'',
    gender: '\'Male\'',
    address: '\'56 Osborn drive, Ikoyi Lagos\'',
  },
  {
    email: '\'odejobiolushola@yahoo.com\'',
    password: '\'$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy\'',
    first_name: '\'Olushola\'',
    last_name: '\'odejobi\'',
    user_type: '\'staff\'',
    is_admin: '\'false\'',
    phone_no: '\'08028955866\'',
    state: '\'Kwara\'',
    city: '\'Ilorin\'',
    occupation: '\'Banker\'',
    gender: '\'Female\'',
    address: '\'Bishop Smith Crescent\'',
  },
  {
    email: '\'odejobiolushola@andela.com\'',
    password: '\'$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy\'',
    first_name: '\'Olushola\'',
    last_name: '\'odejobi\'',
    user_type: '\'admin\'',
    is_admin: '\'true\'',
    phone_no: '\'08028955866\'',
    state: '\'Ondo\'',
    city: '\'Akure\'',
    occupation: '\'Banka Technologist\'',
    gender: '\'Male\'',
    address: '\'Bishop Smith Crescent\'',
  },
  {
    email: '\'shokunbidamilare@gmail.com\'',
    password: '\'$2b$08$1h8dVe10SMH7G1J86x7AM..wdLf0xuEU1Qv8KWU9vCfq/PA0RTAPy\'',
    first_name: '\'Damilare\'',
    last_name: '\'Shokunbi\'',
    user_type: '\'client\'',
    is_admin: '\'false\'',
    phone_no: '\'08066998855\'',
    state: '\'Lagos\'',
    city: '\'Alimosho\'',
    occupation: '\'Trader\'',
    gender: '\'Male\'',
    address: '\'King George V Crescent\'',
  },
];

export default users;
